[package]
name = "miniblink"
version = "0.1.1"
edition = "2021"
authors = ["The miniblink-rs Authors"]
description = "Rust bindings to mininlink49"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/felixmaker/miniblink-rs"
categories = [ "gui" ]
exclude = ["./examples"]

[dependencies]
miniblink-sys = { path = "../miniblink-sys", version = "0.1.1" }
raw-window-handle = { version = "0.6" }

[dev-dependencies]
winit = "0.29"
