name: Rust

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run tests
      run: cargo test --verbose
    - name: Cargo publish miniblink-sys
      run: cargo publish -p miniblink-sys
    - name: Cargo publish miniblink
      run: cargo publish -p miniblink
